[2022-07-21 01:12:25,464] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: process_files.is_postgres_file_available manual__2022-07-21T01:12:09.335529+00:00 [queued]>
[2022-07-21 01:12:25,475] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: process_files.is_postgres_file_available manual__2022-07-21T01:12:09.335529+00:00 [queued]>
[2022-07-21 01:12:25,476] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-21 01:12:25,476] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-07-21 01:12:25,476] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-21 01:12:25,498] {taskinstance.py:1397} INFO - Executing <Task(HttpSensor): is_postgres_file_available> on 2022-07-21 01:12:09.335529+00:00
[2022-07-21 01:12:25,505] {standard_task_runner.py:52} INFO - Started process 1114 to run task
[2022-07-21 01:12:25,507] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'process_files', 'is_postgres_file_available', 'manual__2022-07-21T01:12:09.335529+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/process_files.py', '--cfg-path', '/tmp/tmpo_51shy7', '--error-file', '/tmp/tmpngx9c7rt']
[2022-07-21 01:12:25,507] {standard_task_runner.py:80} INFO - Job 8: Subtask is_postgres_file_available
[2022-07-21 01:12:25,560] {task_command.py:371} INFO - Running <TaskInstance: process_files.is_postgres_file_available manual__2022-07-21T01:12:09.335529+00:00 [running]> on host 4534be881ccc
[2022-07-21 01:12:25,632] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=process_files
AIRFLOW_CTX_TASK_ID=is_postgres_file_available
AIRFLOW_CTX_EXECUTION_DATE=2022-07-21T01:12:09.335529+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-21T01:12:09.335529+00:00
[2022-07-21 01:12:25,633] {http.py:97} INFO - Poking: create_world.sql
[2022-07-21 01:12:25,641] {base.py:68} INFO - Using connection ID 'http_api' for task execution.
[2022-07-21 01:12:25,642] {http.py:129} INFO - Sending 'GET' to url: http://raw.githubusercontent.com/tadinve/EKG-Foundations/master/04A-postgress/create_world.sql
[2022-07-21 01:12:25,856] {http.py:142} ERROR - HTTP error: Not Found
[2022-07-21 01:12:25,856] {http.py:143} ERROR - 404: Not Found
[2022-07-21 01:12:30,863] {http.py:97} INFO - Poking: create_world.sql
[2022-07-21 01:12:30,871] {base.py:68} INFO - Using connection ID 'http_api' for task execution.
[2022-07-21 01:12:30,871] {http.py:129} INFO - Sending 'GET' to url: http://raw.githubusercontent.com/tadinve/EKG-Foundations/master/04A-postgress/create_world.sql
[2022-07-21 01:12:30,939] {http.py:142} ERROR - HTTP error: Not Found
[2022-07-21 01:12:30,939] {http.py:143} ERROR - 404: Not Found
[2022-07-21 01:12:35,946] {http.py:97} INFO - Poking: create_world.sql
[2022-07-21 01:12:35,953] {base.py:68} INFO - Using connection ID 'http_api' for task execution.
[2022-07-21 01:12:35,954] {http.py:129} INFO - Sending 'GET' to url: http://raw.githubusercontent.com/tadinve/EKG-Foundations/master/04A-postgress/create_world.sql
[2022-07-21 01:12:36,028] {http.py:142} ERROR - HTTP error: Not Found
[2022-07-21 01:12:36,029] {http.py:143} ERROR - 404: Not Found
[2022-07-21 01:12:41,034] {http.py:97} INFO - Poking: create_world.sql
[2022-07-21 01:12:41,040] {base.py:68} INFO - Using connection ID 'http_api' for task execution.
[2022-07-21 01:12:41,040] {http.py:129} INFO - Sending 'GET' to url: http://raw.githubusercontent.com/tadinve/EKG-Foundations/master/04A-postgress/create_world.sql
[2022-07-21 01:12:41,106] {http.py:142} ERROR - HTTP error: Not Found
[2022-07-21 01:12:41,106] {http.py:143} ERROR - 404: Not Found
[2022-07-21 01:12:46,112] {http.py:97} INFO - Poking: create_world.sql
[2022-07-21 01:12:46,119] {base.py:68} INFO - Using connection ID 'http_api' for task execution.
[2022-07-21 01:12:46,119] {http.py:129} INFO - Sending 'GET' to url: http://raw.githubusercontent.com/tadinve/EKG-Foundations/master/04A-postgress/create_world.sql
[2022-07-21 01:12:46,189] {http.py:142} ERROR - HTTP error: Not Found
[2022-07-21 01:12:46,190] {http.py:143} ERROR - 404: Not Found
[2022-07-21 01:12:46,191] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 288, in execute
    raise AirflowSensorTimeout(f"Snap. Time is OUT. DAG id: {log_dag_id}")
airflow.exceptions.AirflowSensorTimeout: Snap. Time is OUT. DAG id: process_files
[2022-07-21 01:12:46,199] {taskinstance.py:1420} INFO - Immediate failure requested. Marking task as FAILED. dag_id=process_files, task_id=is_postgres_file_available, execution_date=20220721T011209, start_date=20220721T011225, end_date=20220721T011246
[2022-07-21 01:12:46,215] {standard_task_runner.py:97} ERROR - Failed to execute job 8 for task is_postgres_file_available (Snap. Time is OUT. DAG id: process_files; 1114)
[2022-07-21 01:12:46,237] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-21 01:12:46,275] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
