[2022-07-21 01:16:12,557] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: process_files.is_postgres_file_available manual__2022-07-21T01:15:55.447848+00:00 [queued]>
[2022-07-21 01:16:12,569] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: process_files.is_postgres_file_available manual__2022-07-21T01:15:55.447848+00:00 [queued]>
[2022-07-21 01:16:12,569] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-21 01:16:12,570] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-07-21 01:16:12,570] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-21 01:16:12,590] {taskinstance.py:1397} INFO - Executing <Task(HttpSensor): is_postgres_file_available> on 2022-07-21 01:15:55.447848+00:00
[2022-07-21 01:16:12,597] {standard_task_runner.py:52} INFO - Started process 1443 to run task
[2022-07-21 01:16:12,599] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'process_files', 'is_postgres_file_available', 'manual__2022-07-21T01:15:55.447848+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/process_files.py', '--cfg-path', '/tmp/tmpq_wj90b8', '--error-file', '/tmp/tmp9ez_o64x']
[2022-07-21 01:16:12,599] {standard_task_runner.py:80} INFO - Job 12: Subtask is_postgres_file_available
[2022-07-21 01:16:12,664] {task_command.py:371} INFO - Running <TaskInstance: process_files.is_postgres_file_available manual__2022-07-21T01:15:55.447848+00:00 [running]> on host 4534be881ccc
[2022-07-21 01:16:12,757] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=process_files
AIRFLOW_CTX_TASK_ID=is_postgres_file_available
AIRFLOW_CTX_EXECUTION_DATE=2022-07-21T01:15:55.447848+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-21T01:15:55.447848+00:00
[2022-07-21 01:16:12,757] {http.py:97} INFO - Poking: create_world.sql
[2022-07-21 01:16:12,768] {base.py:68} INFO - Using connection ID 'http_api' for task execution.
[2022-07-21 01:16:12,769] {http.py:129} INFO - Sending 'GET' to url: http://raw.githubusercontent.com/tadinve/EKG-Foundations/master/04A-postgress/create_world.sql
[2022-07-21 01:16:12,993] {http.py:142} ERROR - HTTP error: Not Found
[2022-07-21 01:16:12,993] {http.py:143} ERROR - 404: Not Found
[2022-07-21 01:16:18,000] {http.py:97} INFO - Poking: create_world.sql
[2022-07-21 01:16:18,008] {base.py:68} INFO - Using connection ID 'http_api' for task execution.
[2022-07-21 01:16:18,009] {http.py:129} INFO - Sending 'GET' to url: http://raw.githubusercontent.com/tadinve/EKG-Foundations/master/04A-postgress/create_world.sql
[2022-07-21 01:16:18,082] {http.py:142} ERROR - HTTP error: Not Found
[2022-07-21 01:16:18,083] {http.py:143} ERROR - 404: Not Found
[2022-07-21 01:16:23,086] {http.py:97} INFO - Poking: create_world.sql
[2022-07-21 01:16:23,093] {base.py:68} INFO - Using connection ID 'http_api' for task execution.
[2022-07-21 01:16:23,094] {http.py:129} INFO - Sending 'GET' to url: http://raw.githubusercontent.com/tadinve/EKG-Foundations/master/04A-postgress/create_world.sql
[2022-07-21 01:16:23,170] {http.py:142} ERROR - HTTP error: Not Found
[2022-07-21 01:16:23,170] {http.py:143} ERROR - 404: Not Found
[2022-07-21 01:16:28,176] {http.py:97} INFO - Poking: create_world.sql
[2022-07-21 01:16:28,185] {base.py:68} INFO - Using connection ID 'http_api' for task execution.
[2022-07-21 01:16:28,185] {http.py:129} INFO - Sending 'GET' to url: http://raw.githubusercontent.com/tadinve/EKG-Foundations/master/04A-postgress/create_world.sql
[2022-07-21 01:16:28,260] {http.py:142} ERROR - HTTP error: Not Found
[2022-07-21 01:16:28,260] {http.py:143} ERROR - 404: Not Found
[2022-07-21 01:16:33,266] {http.py:97} INFO - Poking: create_world.sql
[2022-07-21 01:16:33,272] {base.py:68} INFO - Using connection ID 'http_api' for task execution.
[2022-07-21 01:16:33,273] {http.py:129} INFO - Sending 'GET' to url: http://raw.githubusercontent.com/tadinve/EKG-Foundations/master/04A-postgress/create_world.sql
[2022-07-21 01:16:33,334] {http.py:142} ERROR - HTTP error: Not Found
[2022-07-21 01:16:33,335] {http.py:143} ERROR - 404: Not Found
[2022-07-21 01:16:33,336] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 288, in execute
    raise AirflowSensorTimeout(f"Snap. Time is OUT. DAG id: {log_dag_id}")
airflow.exceptions.AirflowSensorTimeout: Snap. Time is OUT. DAG id: process_files
[2022-07-21 01:16:33,345] {taskinstance.py:1420} INFO - Immediate failure requested. Marking task as FAILED. dag_id=process_files, task_id=is_postgres_file_available, execution_date=20220721T011555, start_date=20220721T011612, end_date=20220721T011633
[2022-07-21 01:16:33,361] {standard_task_runner.py:97} ERROR - Failed to execute job 12 for task is_postgres_file_available (Snap. Time is OUT. DAG id: process_files; 1443)
[2022-07-21 01:16:33,393] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-21 01:16:33,436] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
