[2022-07-21 01:06:53,013] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: process_files.is_postgres_file_available scheduled__2022-07-20T00:00:00+00:00 [queued]>
[2022-07-21 01:06:53,022] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: process_files.is_postgres_file_available scheduled__2022-07-20T00:00:00+00:00 [queued]>
[2022-07-21 01:06:53,022] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-21 01:06:53,022] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-07-21 01:06:53,022] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-21 01:06:53,044] {taskinstance.py:1397} INFO - Executing <Task(HttpSensor): is_postgres_file_available> on 2022-07-20 00:00:00+00:00
[2022-07-21 01:06:53,051] {standard_task_runner.py:52} INFO - Started process 771 to run task
[2022-07-21 01:06:53,053] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'process_files', 'is_postgres_file_available', 'scheduled__2022-07-20T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/process_files.py', '--cfg-path', '/tmp/tmpm0zpf1nw', '--error-file', '/tmp/tmp_3es63kz']
[2022-07-21 01:06:53,054] {standard_task_runner.py:80} INFO - Job 5: Subtask is_postgres_file_available
[2022-07-21 01:06:53,132] {task_command.py:371} INFO - Running <TaskInstance: process_files.is_postgres_file_available scheduled__2022-07-20T00:00:00+00:00 [running]> on host 4534be881ccc
[2022-07-21 01:06:53,232] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=process_files
AIRFLOW_CTX_TASK_ID=is_postgres_file_available
AIRFLOW_CTX_EXECUTION_DATE=2022-07-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-20T00:00:00+00:00
[2022-07-21 01:06:53,233] {http.py:97} INFO - Poking: create_world.sql
[2022-07-21 01:06:53,246] {base.py:68} INFO - Using connection ID 'http_api' for task execution.
[2022-07-21 01:06:53,248] {http.py:129} INFO - Sending 'GET' to url: http://raw.githubusercontent.com/tadinve/EKG-Foundations/master/04A-postgress/create_world.sql
[2022-07-21 01:06:53,477] {http.py:142} ERROR - HTTP error: Not Found
[2022-07-21 01:06:53,477] {http.py:143} ERROR - 404: Not Found
[2022-07-21 01:06:58,484] {http.py:97} INFO - Poking: create_world.sql
[2022-07-21 01:06:58,490] {base.py:68} INFO - Using connection ID 'http_api' for task execution.
[2022-07-21 01:06:58,491] {http.py:129} INFO - Sending 'GET' to url: http://raw.githubusercontent.com/tadinve/EKG-Foundations/master/04A-postgress/create_world.sql
[2022-07-21 01:06:58,555] {http.py:142} ERROR - HTTP error: Not Found
[2022-07-21 01:06:58,555] {http.py:143} ERROR - 404: Not Found
[2022-07-21 01:07:03,562] {http.py:97} INFO - Poking: create_world.sql
[2022-07-21 01:07:03,569] {base.py:68} INFO - Using connection ID 'http_api' for task execution.
[2022-07-21 01:07:03,570] {http.py:129} INFO - Sending 'GET' to url: http://raw.githubusercontent.com/tadinve/EKG-Foundations/master/04A-postgress/create_world.sql
[2022-07-21 01:07:03,638] {http.py:142} ERROR - HTTP error: Not Found
[2022-07-21 01:07:03,638] {http.py:143} ERROR - 404: Not Found
[2022-07-21 01:07:08,644] {http.py:97} INFO - Poking: create_world.sql
[2022-07-21 01:07:08,651] {base.py:68} INFO - Using connection ID 'http_api' for task execution.
[2022-07-21 01:07:08,651] {http.py:129} INFO - Sending 'GET' to url: http://raw.githubusercontent.com/tadinve/EKG-Foundations/master/04A-postgress/create_world.sql
[2022-07-21 01:07:08,714] {http.py:142} ERROR - HTTP error: Not Found
[2022-07-21 01:07:08,714] {http.py:143} ERROR - 404: Not Found
[2022-07-21 01:07:13,720] {http.py:97} INFO - Poking: create_world.sql
[2022-07-21 01:07:13,726] {base.py:68} INFO - Using connection ID 'http_api' for task execution.
[2022-07-21 01:07:13,727] {http.py:129} INFO - Sending 'GET' to url: http://raw.githubusercontent.com/tadinve/EKG-Foundations/master/04A-postgress/create_world.sql
[2022-07-21 01:07:13,794] {http.py:142} ERROR - HTTP error: Not Found
[2022-07-21 01:07:13,794] {http.py:143} ERROR - 404: Not Found
[2022-07-21 01:07:13,796] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 288, in execute
    raise AirflowSensorTimeout(f"Snap. Time is OUT. DAG id: {log_dag_id}")
airflow.exceptions.AirflowSensorTimeout: Snap. Time is OUT. DAG id: process_files
[2022-07-21 01:07:13,804] {taskinstance.py:1420} INFO - Immediate failure requested. Marking task as FAILED. dag_id=process_files, task_id=is_postgres_file_available, execution_date=20220720T000000, start_date=20220721T010653, end_date=20220721T010713
[2022-07-21 01:07:13,819] {standard_task_runner.py:97} ERROR - Failed to execute job 5 for task is_postgres_file_available (Snap. Time is OUT. DAG id: process_files; 771)
[2022-07-21 01:07:13,867] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-21 01:07:13,911] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
