[2022-07-21 01:13:57,783] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: process_files.is_postgres_file_available manual__2022-07-21T01:13:41.383742+00:00 [queued]>
[2022-07-21 01:13:57,794] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: process_files.is_postgres_file_available manual__2022-07-21T01:13:41.383742+00:00 [queued]>
[2022-07-21 01:13:57,794] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-21 01:13:57,794] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-07-21 01:13:57,795] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-21 01:13:57,817] {taskinstance.py:1397} INFO - Executing <Task(HttpSensor): is_postgres_file_available> on 2022-07-21 01:13:41.383742+00:00
[2022-07-21 01:13:57,824] {standard_task_runner.py:52} INFO - Started process 1265 to run task
[2022-07-21 01:13:57,826] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'process_files', 'is_postgres_file_available', 'manual__2022-07-21T01:13:41.383742+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/process_files.py', '--cfg-path', '/tmp/tmpjiqqsydb', '--error-file', '/tmp/tmp9fexc70w']
[2022-07-21 01:13:57,826] {standard_task_runner.py:80} INFO - Job 10: Subtask is_postgres_file_available
[2022-07-21 01:13:57,887] {task_command.py:371} INFO - Running <TaskInstance: process_files.is_postgres_file_available manual__2022-07-21T01:13:41.383742+00:00 [running]> on host 4534be881ccc
[2022-07-21 01:13:57,966] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=process_files
AIRFLOW_CTX_TASK_ID=is_postgres_file_available
AIRFLOW_CTX_EXECUTION_DATE=2022-07-21T01:13:41.383742+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-21T01:13:41.383742+00:00
[2022-07-21 01:13:57,966] {http.py:97} INFO - Poking: create_world.sql
[2022-07-21 01:13:57,976] {base.py:68} INFO - Using connection ID 'http_api' for task execution.
[2022-07-21 01:13:57,978] {http.py:129} INFO - Sending 'GET' to url: http://raw.githubusercontent.com/tadinve/EKG-Foundations/master/04A-postgress/create_world.sql
[2022-07-21 01:13:58,165] {http.py:142} ERROR - HTTP error: Not Found
[2022-07-21 01:13:58,165] {http.py:143} ERROR - 404: Not Found
[2022-07-21 01:14:03,170] {http.py:97} INFO - Poking: create_world.sql
[2022-07-21 01:14:03,177] {base.py:68} INFO - Using connection ID 'http_api' for task execution.
[2022-07-21 01:14:03,178] {http.py:129} INFO - Sending 'GET' to url: http://raw.githubusercontent.com/tadinve/EKG-Foundations/master/04A-postgress/create_world.sql
[2022-07-21 01:14:03,243] {http.py:142} ERROR - HTTP error: Not Found
[2022-07-21 01:14:03,243] {http.py:143} ERROR - 404: Not Found
[2022-07-21 01:14:08,246] {http.py:97} INFO - Poking: create_world.sql
[2022-07-21 01:14:08,253] {base.py:68} INFO - Using connection ID 'http_api' for task execution.
[2022-07-21 01:14:08,254] {http.py:129} INFO - Sending 'GET' to url: http://raw.githubusercontent.com/tadinve/EKG-Foundations/master/04A-postgress/create_world.sql
[2022-07-21 01:14:08,319] {http.py:142} ERROR - HTTP error: Not Found
[2022-07-21 01:14:08,320] {http.py:143} ERROR - 404: Not Found
[2022-07-21 01:14:13,326] {http.py:97} INFO - Poking: create_world.sql
[2022-07-21 01:14:13,333] {base.py:68} INFO - Using connection ID 'http_api' for task execution.
[2022-07-21 01:14:13,333] {http.py:129} INFO - Sending 'GET' to url: http://raw.githubusercontent.com/tadinve/EKG-Foundations/master/04A-postgress/create_world.sql
[2022-07-21 01:14:13,427] {http.py:142} ERROR - HTTP error: Not Found
[2022-07-21 01:14:13,428] {http.py:143} ERROR - 404: Not Found
[2022-07-21 01:14:18,434] {http.py:97} INFO - Poking: create_world.sql
[2022-07-21 01:14:18,440] {base.py:68} INFO - Using connection ID 'http_api' for task execution.
[2022-07-21 01:14:18,441] {http.py:129} INFO - Sending 'GET' to url: http://raw.githubusercontent.com/tadinve/EKG-Foundations/master/04A-postgress/create_world.sql
[2022-07-21 01:14:18,511] {http.py:142} ERROR - HTTP error: Not Found
[2022-07-21 01:14:18,511] {http.py:143} ERROR - 404: Not Found
[2022-07-21 01:14:18,513] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 288, in execute
    raise AirflowSensorTimeout(f"Snap. Time is OUT. DAG id: {log_dag_id}")
airflow.exceptions.AirflowSensorTimeout: Snap. Time is OUT. DAG id: process_files
[2022-07-21 01:14:18,521] {taskinstance.py:1420} INFO - Immediate failure requested. Marking task as FAILED. dag_id=process_files, task_id=is_postgres_file_available, execution_date=20220721T011341, start_date=20220721T011357, end_date=20220721T011418
[2022-07-21 01:14:18,539] {standard_task_runner.py:97} ERROR - Failed to execute job 10 for task is_postgres_file_available (Snap. Time is OUT. DAG id: process_files; 1265)
[2022-07-21 01:14:18,550] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-21 01:14:18,606] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
